### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [CatoCoin/CatoCoin#1]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository

File in question:

      CatoCoin/LICENSE

**Comment by CatoCoin** [comment]
CatoCoin intends to comply with all requirements.

**Comment by CatoCoin** [comment]
license file updated

**Comment by Iconoclasta** [comment]
Hey thanks for the collaboration.
The PIVX team will be paying closer attention for copyright violations, which will then allow healthier and mutual relationships with our various forks. We have plans of forming a network we can all mutually benefit from. I would love to keep you in the loop about such progress.

The issue we have found on yours and plenty other repositories is that you've apparently "re-licensed" our code, rather than "sub-licensed". This is so because there is a hierarchy in licensing files and LICENSE is higher than COPYING (please refer to this link to understand what I mean: https://i.imgur.com/l1MgVDo.gif ). To best address this issue I would recommend to either simply delete the LICENSE file (which currently adds no apparent value), or re-purpose the LICENSE file for a different copyright notice than MIT (Apache or GNU for example).

**Comment by CatoCoin** [comment]
Thanks for your feedback. In our research prior to responding to you, we noticed that other coins that were forked from PIVX had no license file at all.

Again thanks and yes, please keep us in the loop.

**Comment by Iconoclasta** [comment]
Apologies for the delay in replying. I have confirmed your repository is now fully compliant. Thank you for your cooperation.

The PIVX project is working on a platform by which PIVX and various other projects (primarily PIVX clones) may come together and share resources. For this reason we have been paying closer attention to our forks (especially those with more potential than others). I believe healthy relationships may only sprout from genuine and respectful grounds, hence the enforcement of the copyright.
